[package]
name = "rust_learn"
version = "0.1.0"
authors = ["Scott Lee <scott.lee@nucleusscientific.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
